#                                                                              #
# ------------------------- WITH CARDANO-NODE  ------------------------------- #
#                                                                              #

FROM cardano-node-ogmios-nodejs:latest as handles-api
WORKDIR /app
ADD ./dist/ ./
ADD entrypoint-node.sh ./entrypoint.sh

SHELL ["/bin/bash", "-c"]

RUN chmod +x entrypoint.sh

EXPOSE 3141

STOPSIGNAL SIGINT
ENTRYPOINT [ "/app/entrypoint.sh" ]
